#!/bin/bash

parsing=
using_json=
filename=
fullpath=

function usage
{
  echo "usage: spaceshark [[-p | --parse] file] [[-o | --open] file]

  parse   Parse a .dat file and open it.
  open    Open an already parsed .json file."
}

# Filename is given as a relative path, make it absolute
function abspath {                                               
      cd "$(dirname $filename)"
      fullpath="$(pwd)/$(basename "$filename")"
      cd "$OLDPWD"
}

while [ "$1" != "" ]; do
  case $1 in
    -p | --parse )        shift
                          parsing=1
                          filename=$1
                          using_json=1
                          abspath
                          ;;
    -o | --open )         shift
                          using_json=1
                          filename=$1
                          abspath
                          fullpath=${fullpath::-5} # Remove .json
                          ;;
    -h | --help )         usage
                          exit
                          ;;
    * )                   usage
                          exit 1
  esac
  shift
done

echo "$1"


if [ "$parsing" = "1" ]; then
  # Run the parser on the input file, remove .dat from
  # the filename
  java -jar spaceshark.jar $fullpath
  fullpath=${fullpath::-4}
fi

if [ "$using_json" = "1" ]; then
  # Application uses tmp chromium directory, pass actual
  # path to file instead
  echo "Launching..."
  # The application will exit immediately if given foo.json
  # Instead pass foo and tack on json in application
  ./app $fullpath
else
  echo "Launching..."
  ./app
fi
